name: Daily Market Script

on:
  schedule:
    - cron: '45 10 * * 1-5'

  workflow_dispatch:
    inputs:
      content_type:
        description: "Choose Content Type"
        required: true
        default: "video"
        type: choice
        options:
          - video
          - short

jobs:
  market-news:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CONTENT_TYPE: ${{ github.event.inputs.content_type || 'video' }}
        run: python main.py

      - name: Commit Posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add posts/

          git commit -m "Add daily market post" || echo "No changes"

          git push
